#!/usr/bin/env bash

# ===========================================
# ===========================================
BASEDIR="$HOME/my_root_project_folder"
PORT=$1

# =========================================== The main variables:
SCRIPT_FOLDER="price_tag"
VENV_FOLDER=".venv_project"
RUN_PY="run_script" # Python file where the script is initialized (if __name__ == '__main__':).
PYTHON_PROCESS_PID=0
# =========================================== Color codes:
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color
# ===========================================
# ===========================================
echo -e "${GREEN}Launching the application $SCRIPT_FOLDER, testing is in progress:${NC}"

# Activating the virtual environment:
source "$BASEDIR/$SCRIPT_FOLDER/$VENV_FOLDER/bin/activate"

# Going to the directory with the script:
cd "$BASEDIR/$SCRIPT_FOLDER" 

# Running a Python script (executive file):
python "$RUN_PY.py" "$PORT" 

# The script has finished working
echo -e "${GREEN}The application has been stopped!${NC}"
# ===========================================
# ===========================================
